import { ToolRegistry, type ToolDefinition } from "../agent/toolRegistry.js";
import { signalTools } from "./signal/index.js";
import { linkTools } from "./link/index.js";
import { graphTools } from "./graph/index.js";
import { constellationTools } from "./constellation/index.js";
import { subagentTools } from "./subagent/index.js";
import { consentTools } from "./consent/index.js";
import { sourceConnectorTools, sourceConnectorToolNames } from "./sources/connectorTools.js";
import { buildBreadthTools } from "./breadth.js";

/**
 * Assemble the full tool registry. Chain-critical tools have real fixture-backed
 * handlers; the remaining namespaced tools are generated by `buildBreadthTools`
 * with a uniform mock handler. Either way, every tool carries full metadata and
 * is selected through the registry — never a hand-written dispatch.
 */
export function createToolRegistry(): ToolRegistry {
  const registry = new ToolRegistry();

  const core: ToolDefinition<any, any>[] = [
    ...signalTools,
    ...linkTools,
    ...graphTools,
    ...constellationTools,
    ...subagentTools,
    ...consentTools,
    ...sourceConnectorTools,
  ];
  registry.registerAll(core);

  const existing = new Set([...core.map((t) => t.name), ...sourceConnectorToolNames]);
  registry.registerAll(buildBreadthTools(existing));

  return registry;
}

export { signalTools, linkTools, graphTools, constellationTools, subagentTools, consentTools };
